# Generated by Django 4.1.1 on 2022-09-22 11:47

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, choices=[('1', 'Man'), ('2', 'Woman'), ('3', 'Kids')], max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=355, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_totel_stoke', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_sub_category', to='category.category')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_brand', to='category.brand')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('title', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('images2', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('sub_product_totel_stoke', models.IntegerField(blank=True, null=True)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_persentage', models.FloatField(blank=True, null=True)),
                ('offer_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_reference_main_product', to='product.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.section')),
            ],
            options={
                'verbose_name_plural': 'sub Product Attribute',
            },
        ),
        migrations.CreateModel(
            name='SubProductAttributeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_images_reference_sub_product', to='product.subproductattribute')),
            ],
            options={
                'verbose_name_plural': 'sub product attribute image',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Quantity_referece_offer_product', to='product.subproductattribute')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_color_reference_sub_product', to='category.color')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_size_reference_sub_product', to='category.size')),
            ],
            options={
                'verbose_name_plural': 'Product Quantity',
            },
        ),
    ]
