# Generated by Django 4.1.1 on 2022-09-26 07:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=255, null=True, unique_with=('product_name', 'sku')),
        ),
    ]
