# Generated by Django 4.1.2 on 2022-10-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.CharField(max_length=250),
        ),
    ]
