# Generated by Django 4.1.2 on 2022-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraddress_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
