# Generated by Django 4.1.2 on 2022-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraddress_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='alt_phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
