# Generated by Django 4.1.2 on 2022-10-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraddress_alt_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='alt_phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
