# Generated by Django 4.1.2 on 2022-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone_no_alter_useraddress_alt_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
