# Generated by Django 4.1.1 on 2022-09-26 05:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='category', unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='Size', unique=True),
        ),
    ]
