# Generated by Django 4.1.1 on 2022-09-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_product', to='product.subproductattribute'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_product_quantity', to='product.productquantity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_is_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
