# Generated by Django 4.1.1 on 2022-09-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_slug'),
        ('cart', '0004_whishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subproductattribute'),
        ),
    ]
