# Generated by Django 4.1.1 on 2022-09-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_whishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whishlist',
        ),
    ]
